# This is a config for E2B sandbox template.
# You can use template ID (k0x28ycrakwwre0gsbi0) or template name (wow-ui) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("wow-ui") # Sync sandbox
# sandbox = await AsyncSandbox.create("wow-ui") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('wow-ui')

team_id = "128f60e4-0aa5-478a-95d0-eee5e1b47837"
start_cmd = "C:/Program Files/Git/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "wow-ui"
template_id = "k0x28ycrakwwre0gsbi0"
